# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Vocablii"
  lane :deploy do
    increment_build_number

    get_certificates(username: "johann123.js@gmail.com")
    get_provisioning_profile(app_identifier: 'com.navabase.vocablii', username: "johann123.js@gmail.com")
    
    build_ios_app # build_ios_app is a built-in fastlane action.

    deliver(
      username: 'johann123.js@gmail.com',
      app_identifier: 'com.navabase.vocablii',
      app_version: '1.0.1',
      submit_for_review: true,
      automatic_release: true,
      force: true, # Skip HTMl report verification
      skip_metadata: true,
      skip_screenshots: true,
      skip_binary_upload: false
    )

  end

  lane :firebase do
    get_certificates(username: "johann123.js@gmail.com")
    get_provisioning_profile(app_identifier: 'com.navabase.vocablii', username: "johann123.js@gmail.com")
    
    build_ios_app # build_ios_app is a built-in fastlane action.

    firebase_app_distribution(
      groups: "Developers, Testers",		
      release_notes: "Lots of amazing new features to test out!"		
    )
  end
end