on:
  push:
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: test the app
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with: 
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
            channel: "stable"

      - run: flutter pub get
      - run: flutter build apk
      - run: flutter build ios --release --no-codesign

      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'test'
          subdirectory: 'ios'
          bundle-install-path: 'ios/Gemfile'
          skip-tracking: true

      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'test'
          subdirectory: 'android'
          bundle-install-path: 'android/Gemfile'
          skip-tracking: true