name: 'deploy app'

'on':
  push:
    branches:
      - develop
      
jobs:
  distribute:
    runs-on: macos-latest
    steps:
      - name: upload ipa
      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'deploy'
          subdirectory: 'ios'
      - name: upload apk
      - uses: maierj/fastlane-action@v1.4.0
        with:
          lane: 'deploy'
          subdirectory: 'android'